name: PathSeg
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - scikit-image
  - opencv
  - pandas
  - pillow
  - numpy
  - openslide
  - openslide-python
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=11.8
  - albumentations
  - pip
  - pip:
      - transformers==4.46.1
      - pycocotools
      - matplotlib
      - scikit-learn
      - accelerate==0.26.0
